### ISSUE TITLE
Leading zeroes eliminated in census block csv output

### ISSUE THREAD

**Issue by sneharav15** [degauss-org/census_block_group#26] opened 2022-07-28 20:49 UTC
Hello,

Hope you are well. I just wanted to notify you of an issue that I am seeing. Many census block group numbers generated in the csv file output have 11 digits instead of 12. These are the states with 11 digit zip codes: AL, AR, CO, AZ, CA, AK. An example is Geocode AK: 020200009013, however, saved as: 20200009013. It looks like the saved csv output does not keep the leading zeroes. Is there a way to incorporate this fix this in de-gauss census_block_group? If not, I can look into fixing it on our end. Thanks!

**Comment by cole-brokamp** [comment] 2022-07-29 16:59
Thanks for your message!  In order for us to best help you, please create a [minimal reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) of the error, bug, or issue that you are encountering.

An MRE is intended to reproduce an error using the smallest amount of code, which will save troubleshooting time and effort. It also ensures that the problem is related to code in this repository, as opposed to other software tools being used alongside DeGAUSS or to your specific input data.  Once we can reproduce the specific problem, then we can work to troubleshoot it.

DeGAUSS is often used with sensitive and private data that cannot be shared, so using a contrived, random, or simulated example dataset might be necessary.  Every DeGAUSS repository has [test](https://github.com/degauss-org/geocoder/blob/master/test/my_address_file.csv) [input](https://github.com/degauss-org/census_block_group/blob/master/test/my_address_file_geocoded.csv) files that are useful for troubleshooting and trying to create a MRE.

**Comment by cole-brokamp** [comment] 2022-08-16 20:22
closing for now, but please reopen if necessary.

**Closed as completed by cole-brokamp** 2022-08-16 20:22 UTC
